apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-operations-database
  namespace: workshop-n-gine
spec:
  selector:
    matchLabels:
      app: service-operations-database
  serviceName: service-operations-database
  replicas: 1
  updateStrategy:
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: service-operations-database
    spec:
      containers:
        - name: mysql
          image: mysql:9.2.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "1Gi"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: service-operations-database-secrets
                  key: mysql_db
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: service-operations-database-secrets
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-operations-database-secrets
                  key: mysql_password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-operations-database-secrets
                  key: mysql_root_password
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: service-operations-init-db
            - mountPath: /var/lib/mysql
              name: service-operations-database-data
              subPath: service_operations
      volumes:
        - name: service-operations-init-db
          configMap:
            name: service-operations-database-config
        - name: service-operations-database-data
          persistentVolumeClaim:
            claimName: service-operations-database-claim

---

apiVersion: v1
kind: Secret
metadata:
  name: service-operations-database-secrets
  namespace: workshop-n-gine
data:
  mysql_db: c2VydmljZV9vcGVyYXRpb25z
  mysql_password: cGFzc3dvcmQxMjM=
  mysql_root_password: cGFzc3dvcmQxMjM0NQ==
  mysql_user: amhvc2VwbXly

---

apiVersion: v1
kind: Service
metadata:
  name: service-operations-database
  namespace: workshop-n-gine
  labels:
    app: service-operations-database
spec:
  ports:
    - name: service-operations-database
      port: 3305
      protocol: TCP
      targetPort: 3306
  selector:
    app: service-operations-database
  type: ClusterIP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-operations-database-claim
  namespace: workshop-n-gine
  labels:
    app: service-operations-database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: service-operations-database-config
  namespace: workshop-n-gine
  labels:
    app: service-operations-database
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS service_operations;