apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: workshop-database
  namespace: workshop-n-gine
spec:
  selector:
    matchLabels:
      app: workshop-database
  serviceName: workshop-database
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: workshop-database
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: workshop-database
                  key: postgres_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: workshop-database
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: workshop-database
                  key: postgres_password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: workshop-database-data
              subPath: data
      volumes:
        - name: workshop-init-db
          configMap:
            name: workshop-database-config
        - name: workshop-database-data
          persistentVolumeClaim:
            claimName: workshop-database-volume-claim

---

apiVersion: v1
kind: Secret
metadata:
  name: workshop-database
  namespace: workshop-n-gine
data:
  postgres_db: d29ya3Nob3Bz
  postgres_password: cGFzc3dvcmQ=
  postgres_user: dXNlcg==

---

apiVersion: v1
kind: Service
metadata:
  name: workshop-database
  namespace: workshop-n-gine
  labels:
    app: workshop-database
spec:
  ports:
    - name: 5432-5432
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: workshop-database
  type: ClusterIP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workshop-database-volume-claim
  namespace: workshop-n-gine
  labels:
    app: workshop-database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: workshop-database-volume
  labels:
    type: local
    app: workshop-database
spec:
    storageClassName: manual
    capacity:
        storage: 0.1Gi
    accessModes:
        - ReadWriteMany
    hostPath:
      path: "/data/workshop-database"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: workshop-database-config
  namespace: workshop-n-gine
  labels:
    app: workshop-database
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS workshops;

---

# RUNNING: kubectl apply -f k8s/manifests/infrastructure/workshop-database.yaml